import { Injectable } from '@angular/core';
import { InMemoryDbService } from 'angular-in-memory-web-api';

@Injectable({
  providedIn: 'root',
})
export class MockWebApiService implements InMemoryDbService {
  constructor() {}

  createDb() {
    return {
      league: [
        {
          id: 1,
          leagueName: 'catBloomLeague',
          leagueManual: '大会の説明',
          leagueStartDate: 'Sat Apr 04 2022 22:00:00 GMT+0900 (日本標準時)',
          leagueFinishDate: 'Sat Apr 30 2022 22:00:00 GMT+0900 (日本標準時)',
        },
        {
          id: 2,
          leagueName: 'sample2League',
          leagueManual: '大会の説明',
          leagueStartDate: 'Sat Apr 06 2022 01:00:00 GMT+0900 (日本標準時)',
          leagueFinishDate: 'Sat Apr 30 2022 09:00:00 GMT+0900 (日本標準時)',
        },
      ],
      rules: [
        {
          id: 1,
          leagueId: 1,
          radioGame: '1',
          radioDora: '1',
          radioTanyao: '1',
          radioTime: '1',
          inputStartPoint: 25000,
          inputFinishPoint: 30000,
          inputReturnPoint: 25000,
          inputCalledPoint: 0,
          inputReachPoint: 1000,
          inputDeposit: 300,
          inputPenalty1: 1000,
          inputPenalty2: 1500,
          inputPenalty3: 3000,
          inputUma1: 10,
          inputUma2: 5,
          inputUma3: -5,
          inputUma4: -10,
        },
        {
          id: 2,
          leagueId: 2,
          radioGame: '2',
          radioDora: '3',
          radioTanyao: '2',
          radioTime: '2',
          inputStartPoint: 25000,
          inputFinishPoint: 30000,
          inputReturnPoint: 25000,
          inputCalledPoint: 0,
          inputReachPoint: 1000,
          inputDeposit: 300,
          inputPenalty1: 1000,
          inputPenalty2: 1500,
          inputPenalty3: 3000,
          inputUma1: 20,
          inputUma2: 15,
          inputUma3: -15,
          inputUma4: -20,
        },
      ],
      player: [
        {
          id: 1,
          leagueId: 1,
          playerName: 'catBloom',
          playerGameCount: 34,
          playerCalcPoint: 200.5,
          playerAverage: 2.3,
        },
        {
          id: 2,
          leagueId: 1,
          playerName: 'player2',
          playerGameCount: 34,
          playerCalcPoint: 190.5,
          playerAverage: 2.4,
        },
        {
          id: 3,
          leagueId: 1,
          playerName: 'player3',
          playerGameCount: 34,
          playerCalcPoint: -15,
          playerAverage: 2.6,
        },
        {
          id: 4,
          leagueId: 1,
          playerName: 'player4',
          playerGameCount: 34,
          playerCalcPoint: -15,
          playerAverage: 2.7,
        },
      ],
      result: [
        {
          id: 1,
          leagueId: 1,
          rank: 1,
          createDate: new Date('Sat Apr 02 2022 22:00:00 GMT+0900 (日本標準時)'),
          group: 1,
          resultData: [
            {
              id: 1,
              rank: 1,
              leagueId: 1,
              playerId: 1,
              playerName: 'catBloom',
              point: 40000,
              calcPoint: 40,
              createDate: new Date('2020/02/02'),
              group: 1,
            },
            {
              id: 2,
              rank: 2,
              leagueId: 1,
              playerId: 2,
              playerName: 'sample02',
              point: 30000,
              calcPoint: 30,
              createDate: new Date('2020/02/02'),
              group: 1,
            },
            {
              id: 3,
              rank: 3,
              leagueId: 1,
              playerId: 3,
              playerName: 'sample03',
              point: 20000,
              calcPoint: 20,
              createDate: new Date('2020/02/02'),
              group: 1,
            },
            {
              id: 4,
              rank: 4,
              leagueId: 1,
              playerId: 4,
              playerName: 'sample04',
              point: 10000,
              calcPoint: 10,
              createDate: new Date('2020/02/02'),
              group: 1,
            },
          ],
        },
        {
          id: 5,
          rank: 2,
          leagueId: 1,
          createDate: new Date('Sat Apr 02 2022 23:00:00 GMT+0900 (日本標準時)'),
          group: 2,
          resultData: [
            {
              id: 6,
              rank: 1,
              leagueId: 1,
              playerId: 4,
              playerName: 'sample04',
              point: 60000,
              calcPoint: 40,
              createDate: new Date('2020/02/03'),
              group: 2,
            },
            {
              id: 7,
              rank: 2,
              leagueId: 1,
              playerId: 1,
              playerName: 'catBloom',
              point: 25000,
              calcPoint: 30,
              createDate: new Date('2020/02/03'),
              group: 2,
            },
            {
              id: 7,
              rank: 3,
              leagueId: 1,
              playerId: 3,
              playerName: 'sample03',
              point: 20000,
              calcPoint: 20,
              createDate: new Date('2020/02/03'),
              group: 2,
            },
            {
              id: 8,
              rank: 4,
              leagueId: 1,
              playerId: 2,
              playerName: 'sample02',
              point: -5000,
              calcPoint: 10,
              createDate: new Date('2020/02/03'),
              group: 2,
            },
          ],
        },
      ],
      leagueResult: [
        {
          id: 1,
          leagueId: 1,
          rank: 1,
          playerId: 1,
          playerName: 'CatBloom',
          playerGameCount: 34,
          playerCalcPoint: 200.5,
          date: new Date('Sat Apr 30 2022 22:00:00 GMT+0900 (日本標準時)'),
        },
        {
          id: 2,
          leagueId: 1,
          rank: 2,
          playerId: 2,
          playerName: 'sample02',
          playerGameCount: 34,
          playerCalcPoint: 190.5,
          date: new Date('Sat Apr 30 2022 22:00:00 GMT+0900 (日本標準時)'),
        },
        {
          id: 3,
          leagueId: 1,
          rank: 3,
          playerId: 3,
          playerName: 'sample03',
          playerGameCount: 34,
          playerCalcPoint: -15,
          date: new Date('Sat Apr 30 2022 22:00:00 GMT+0900 (日本標準時)'),
        },
        {
          id: 4,
          leagueId: 1,
          rank: 4,
          playerId: 4,
          playerName: 'sample04',
          playerGameCount: 34,
          playerCalcPoint: -100,
          date: new Date('Sat Apr 30 2022 22:00:00 GMT+0900 (日本標準時)'),
        },
      ],
      playerResult: [
        {
          id: 1,
          leagueId: 1,
          playerId: 1,
          rank: 1,
          playerName: 'catBloom',
          createDate: new Date('Sat Apr 02 2022 22:00:00 GMT+0900 (日本標準時)'),
          group: 1,
          resultData: [
            {
              id: 1,
              rank: 1,
              leagueId: 1,
              playerId: 1,
              playerName: 'catBloom',
              point: 40000,
              calcPoint: 40,
              createDate: new Date('2020/02/02'),
              group: 1,
            },
            {
              id: 2,
              rank: 2,
              leagueId: 1,
              playerId: 2,
              playerName: 'sample02',
              point: 30000,
              calcPoint: 30,
              createDate: new Date('2020/02/02'),
              group: 1,
            },
            {
              id: 3,
              rank: 3,
              leagueId: 1,
              playerId: 3,
              playerName: 'sample03',
              point: 20000,
              calcPoint: 20,
              createDate: new Date('2020/02/02'),
              group: 1,
            },
            {
              id: 4,
              rank: 4,
              leagueId: 1,
              playerId: 4,
              playerName: 'sample04',
              point: 10000,
              calcPoint: 10,
              createDate: new Date('2020/02/02'),
              group: 1,
            },
          ],
        },
        {
          id: 5,
          rank: 2,
          leagueId: 1,
          playerId: 1,
          playerName: 'catBloom',
          point: 20000,
          calcPoint: 30,
          createDate: new Date('Sat Apr 02 2022 23:00:00 GMT+0900 (日本標準時)'),
          group: 2,
          resultData: [
            {
              id: 6,
              rank: 1,
              leagueId: 1,
              playerId: 4,
              playerName: 'sample04',
              point: 60000,
              calcPoint: 40,
              createDate: new Date('2020/02/03'),
              group: 2,
            },
            {
              id: 7,
              rank: 2,
              leagueId: 1,
              playerId: 1,
              playerName: 'catBloom',
              point: 25000,
              calcPoint: 30,
              createDate: new Date('2020/02/03'),
              group: 2,
            },
            {
              id: 7,
              rank: 3,
              leagueId: 1,
              playerId: 3,
              playerName: 'sample03',
              point: 20000,
              calcPoint: 20,
              createDate: new Date('2020/02/03'),
              group: 2,
            },
            {
              id: 8,
              rank: 4,
              leagueId: 1,
              playerId: 2,
              playerName: 'sample02',
              point: -5000,
              calcPoint: 10,
              createDate: new Date('2020/02/03'),
              group: 2,
            },
          ],
        },
      ],
    };
  }
}
